# path to a directory with all packages
storage: ../tmp/local-registry/storage

packages:
  '**':
    access: $all
    publish: $all
    unpublish: $all

# log settings
log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true

search:
  web:
    enable: true
